# Project: oop_superMartFinal
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe -D__DEBUG__
CC       = gcc.exe -D__DEBUG__
WINDRES  = windres.exe
OBJ      = admin.o cart.o inventory.o customer.o item.o main.o
LINKOBJ  = admin.o cart.o inventory.o customer.o item.o main.o
LIBS     = -L"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib" -L"C:/Program Files (x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc -pg -g3
INCS     = -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = oop_superMartFinal.exe
CXXFLAGS = $(CXXINCS) -std=c++11 -pg -g3
CFLAGS   = $(INCS) -std=c++11 -pg -g3
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

admin.o: admin.cpp
	$(CPP) -c admin.cpp -o admin.o $(CXXFLAGS)

cart.o: cart.cpp
	$(CPP) -c cart.cpp -o cart.o $(CXXFLAGS)

inventory.o: inventory.cpp
	$(CPP) -c inventory.cpp -o inventory.o $(CXXFLAGS)

customer.o: customer.cpp
	$(CPP) -c customer.cpp -o customer.o $(CXXFLAGS)

item.o: item.cpp
	$(CPP) -c item.cpp -o item.o $(CXXFLAGS)

main.o: main.cpp
	$(CPP) -c main.cpp -o main.o $(CXXFLAGS)
